export const GET_TO_USERDATA = 'GET_TO_USERDATA';
export const ADD_TO_COUNT = 'ADD_TO_COUNT';
export const GET_TO_MODULEMENU = 'GET_TO_MODULEMENU';
export const GET_TO_TERMINALSTATIONS = 'GET_TO_TERMINALSTATIONS';
export const GET_TO_USERSTATIONS = 'GET_TO_USERSTATIONS';
export const GET_TO_OPERSTATIONS = 'GET_TO_OPERSTATIONS';
//userimformation 常量

export const SET_TO_HEADTITLE = 'SET_TO_HEADTITLE'

